// Fetch one relevant Qur'anic ayah per prophet from alquran.cloud (authentic
// source), with Arabic (Uthmani), English (Sahih International), Urdu
// (Junagarhi) translations and the Al-Afasy recitation audio. Downloads the
// recitation mp3 into public/audio/ayah/ and writes app/data/prophets-ayah.js.
//
// The verse REFERENCES below are an editorial mapping (which ayah suits which
// prophet); the TEXT and audio always come verified from the API.
//
// Run:  node scripts/fetch-ayat.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const AUDIO_DIR = path.join(ROOT, "public", "audio", "ayah");
const OUT_FILE = path.join(ROOT, "app", "data", "prophets-ayah.js");

// prophet id -> list of "surah:ayah" (3-4 relevant, well-known verses each).
const REFS = {
  1:  ["2:30", "2:34", "2:37", "7:23"],
  2:  ["19:56", "19:57", "21:85"],
  3:  ["7:59", "11:48", "29:14", "54:10"],
  4:  ["7:65", "11:50", "11:56"],
  5:  ["7:73", "11:64", "26:155"],
  6:  ["6:79", "21:69", "2:127", "2:131"],
  7:  ["21:74", "26:161", "37:133"],
  8:  ["19:54", "37:102", "2:127"],
  9:  ["37:112", "37:113", "21:72"],
  10: ["12:18", "12:86", "12:87"],
  11: ["12:4", "12:90", "12:92", "12:101"],
  12: ["21:83", "21:84", "38:44"],
  13: ["7:85", "11:85", "26:181"],
  14: ["20:14", "20:25", "26:62", "28:7"],
  15: ["19:53", "20:30", "25:35"],
  16: ["21:85", "21:86", "38:48"],
  17: ["34:10", "38:26", "21:79"],
  18: ["27:16", "27:19", "27:30"],
  19: ["37:123", "37:125", "6:85"],
  20: ["6:86", "38:47", "38:48"],
  21: ["21:87", "21:88", "37:139", "68:48"],
  22: ["3:38", "19:4", "21:89"],
  23: ["19:12", "19:13", "19:14", "3:39"],
  24: ["19:30", "19:31", "3:45"],
  25: ["68:4", "21:107", "33:21", "3:159"],
};
const EDITIONS = "quran-uthmani,en.sahih,ur.junagarhi,ar.alafasy";

async function getJson(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error("HTTP " + r.status + " for " + url);
  return r.json();
}

async function download(url, dest) {
  const r = await fetch(url);
  if (!r.ok) throw new Error("audio HTTP " + r.status);
  const buf = Buffer.from(await r.arrayBuffer());
  fs.writeFileSync(dest, buf);
  return buf.length;
}

async function main() {
  fs.mkdirSync(AUDIO_DIR, { recursive: true });
  const out = {};
  let total = 0;
  for (const id of Object.keys(REFS)) {
    out[id] = [];
    for (const ref of REFS[id]) {
      const data = (await getJson(`https://api.alquran.cloud/v1/ayah/${ref}/editions/${EDITIONS}`)).data;
      const byId = {};
      for (const e of data) byId[e.edition.identifier] = e;
      const ar = byId["quran-uthmani"];
      const en = byId["en.sahih"];
      const ur = byId["ur.junagarhi"];
      const rec = byId["ar.alafasy"];
      const surahNo = ar.surah.number, ayahNo = ar.numberInSurah;
      const file = `${surahNo}_${ayahNo}.mp3`;
      const bytes = await download(rec.audio, path.join(AUDIO_DIR, file));
      out[id].push({
        ref: `${ar.surah.englishName} · ${surahNo}:${ayahNo}`,
        ar: ar.text, en: en.text, ur: ur.text,
        audio: `/audio/ayah/${file}`,
      });
      total++;
      console.log(`✓ #${id}  ${ref}  ${ar.surah.englishName} ${surahNo}:${ayahNo}  (${(bytes / 1024).toFixed(0)}KB)`);
    }
  }
  console.log(`Fetched ${total} verses across ${Object.keys(out).length} prophets.`);
  const body =
    "// Qur'anic ayat per prophet (3-4 each) — fetched from alquran.cloud (Uthmani\n" +
    "// text, Sahih International EN, Junagarhi UR, Al-Afasy recitation). Each value\n" +
    "// is an array of verses. Generated by scripts/fetch-ayat.mjs — re-run to update.\n" +
    "export const PROPHET_AYAH = " + JSON.stringify(out, null, 2) + ";\n";
  fs.writeFileSync(OUT_FILE, body);
  console.log(`Wrote ${OUT_FILE}.`);
}
main().catch((e) => { console.error(e); process.exit(1); });
